In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv("C:\\Users\\sanch\\OneDrive\\Desktop\\Movie-Recommendation-System\\data\\feature_engineered_movies.csv")
print('Dataset Loaded')

Dataset Loaded

In [3]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"['In', 'the', '22nd', 'century,', 'a', 'parapl...","['Action', 'Adventure', 'Fantasy', 'ScienceFic...","['cultureclash', 'future', 'spacewar', 'spacec...","['SamWorthington', 'ZoeSaldana', 'SigourneyWea...",['JamesCameron'],"['In', 'the', '22nd', 'century,', 'a', 'parapl..."
1,285,Pirates of the Caribbean: At World's End,"['Captain', 'Barbossa,', 'long', 'believed', '...","['Adventure', 'Fantasy', 'Action']","['ocean', 'drugabuse', 'exoticisland', 'eastin...","['JohnnyDepp', 'OrlandoBloom', 'KeiraKnightley']",['GoreVerbinski'],"['Captain', 'Barbossa,', 'long', 'believed', '..."
2,206647,Spectre,"['A', 'cryptic', 'message', 'from', 'Bond’s', ...","['Action', 'Adventure', 'Crime']","['spy', 'basedonnovel', 'secretagent', 'sequel...","['DanielCraig', 'ChristophWaltz', 'LéaSeydoux']",['SamMendes'],"['A', 'cryptic', 'message', 'from', 'Bond’s', ..."
3,49026,The Dark Knight Rises,"['Following', 'the', 'death', 'of', 'District'...","['Action', 'Crime', 'Drama', 'Thriller']","['dccomics', 'crimefighter', 'terrorist', 'sec...","['ChristianBale', 'MichaelCaine', 'GaryOldman']",['ChristopherNolan'],"['Following', 'the', 'death', 'of', 'District'..."
4,49529,John Carter,"['John', 'Carter', 'is', 'a', 'war-weary,', 'f...","['Action', 'Adventure', 'ScienceFiction']","['basedonnovel', 'mars', 'medallion', 'spacetr...","['TaylorKitsch', 'LynnCollins', 'SamanthaMorton']",['AndrewStanton'],"['John', 'Carter', 'is', 'a', 'war-weary,', 'f..."

In [23]:
new_df = movies[['movie_id','title','tags']]

In [24]:
new_df['tags'] = new_df['tags'].apply(lambda x:' '.join(x))

C:\Users\sanch\AppData\Local\Temp\ipykernel_4544\2266712157.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:' '.join(x))

In [25]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[ ' I n ' , ' t h e ' , ' 2 2 n d ' , ' ..."
1,285,Pirates of the Caribbean: At World's End,"[ ' C a p t a i n ' , ' B a r b o s s a , ' ..."
2,206647,Spectre,"[ ' A ' , ' c r y p t i c ' , ' m e s s a ..."
3,49026,The Dark Knight Rises,"[ ' F o l l o w i n g ' , ' t h e ' , ' d ..."
4,49529,John Carter,"[ ' J o h n ' , ' C a r t e r ' , ' i s ' ..."

In [ ]:
new_df['tags'][0]

In [ ]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [ ]:
new_df.head()

In [4]:
movies = pd.read_csv("C:\\Users\\sanch\\OneDrive\\Desktop\\Movie-Recommendation-System\\data\\feature_engineered_movies.csv")
print('Dataset Loaded')

Dataset Loaded

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [6]:
vector = cv.fit_transform(new['tags']).toarray()

NameError: name 'new' is not defined